travis:
  secure:
    BINSTAR_TOKEN: dFPqXORImO7extpb1fSlj9gwQjUS5ZNCmHmlkz9VC6QMXUAONap8OyarK99SOXPRaBSzhzXjKwnWA12A/x9hhAbkLbyUZQ+yfFB5iglzXkMUPnKARjUVnZK9u2kkNBkEZzsLxpprpdm17DkB1FI0x84jwZ3BwrKGqm5c4GEri81isW/nwHMpkPX0GrILMQe/hN1WHrpUIdVQXv36etHCjfrv3y0d6psOCgmQYu8ej8yvZo+G5aUnZYEKrn3eGCLEVf77flO6blzZ5Gjsv09SMNjnLLt8ZiVzyp292bt1gP0kj0I77I5OnlvCWyBaGIwl07tJIQv0sKkijSx/IitmuOQVrn9Vbflxu5+qxJVqFdhaCDwqzViWnPZjYhDUORVE+ulIMYdSQruYsTyWR7sECf2UioJEoNiOWfuJ9eZc4oivCt7yTfQNRPVDb0fCz2ppuvLgZfpSEvf5qRQvX1TRkP8c7LSQ74/fgPougINyIWgmYzjmZLp0Bbo+grWrCUTN7VbeG0VGgTbUZBmDI1J3ezpEO7U3wSRf4EsAP01Kp7bPP1wzOf4C1Ty9/sxf3fNCeaCgfYpIHFV7krPE3wDoRck4kV66+HnhBV+b3JSszkaXLEKopgtIywZmqXgmq7ja+gkqqd60HSJnezlDWnwEThKEL+xiQNZWPjwLM52L4f8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
