travis:
  secure:
    BINSTAR_TOKEN: sUyd/hksQEyOmKBImWA3fEKYWiqnq7vyUSwvX3ysa1MnSequWhpYpFm1cA4UHJeudPVpQqu5GLsTDGacSt93vJg8WpOj8PEGSg0T41kT8DEAbcCzelkqb3gJfBW0Wl7HlWFX0d1KJkI3yu4RjKz6b1fiInVx78Mz94K5hzke0t7Cm8i+JgGuWB1ywjFM7AcT0CRs0XWxmG63wF8nPSu6FmD9JsGV+Ld9f+w4KDMKFCbV1zqjrk0QxbpqfUytIrPM3fbbh4L3M2gUiAUc4GrXcUuQHilo80OraMlzi5oZQDP0Tbpc/W72NtrVpfOw/kTNrqlOpqLwgKWcMsE6ftr0VpnGsSY+CPxZ0PFJnovGOAx5+UWdqOvHfORb64cf7FTdpUZC3yQqBcoShX9KpuHyBbE2SVBvBBPq1Jux3IobQSoCIzwLCK3E1GqRqPuYGa9j/71AzzohHNJq+wAi6pcxXFFLnBsrWmnoM4UzqhNNpklBTGYC1FotKjXgdaRZkDwQT9vMIyTZUkvht86T+OwVmsDBPVgqseKyzatIMpTBldo6+LaA3A64HgZ3d7+ntSX5yMAF2iGN2Rlbqj+4pTFZxM81viaqoq0k3ensSmoDN7FDmX2PMI0pW5T1P7ZFIa8Jj9cIkPjG6fnGx6omjsWpoRSpiPJY+G2LqxeKGbOfolA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
