travis:
  secure:
    BINSTAR_TOKEN: YFd8PhSmGSzEJ3xYu+Hzww3oJlzIX9MbJrIn+8xJXzVQPv+jEa5NPidwNlt/Az9PebKPf9Ue4W/WJfy9a5jsDcqFybJp/l6/FCB2c541kI6JcRIR7UU9Dze0EpvckFD54fKejrGDEWzVhRm+S+Sk+itZqy0xPDiVtWnGeEVpg79ZRqrsNO1/dV2SZA2Xbv9kh7F+O1my7Qs0VOInEVbU9TFSLGQD0+5WtJAYwkDiE3q9gQvpqhAmm+bJqzTXCc/+0FpAC1nCwUSDYBbj0uudZ0phyYdj3gzqnHbM8XaYMokx66cwpLe7i2fq9fkHVv0MY4CR2+O64vH0iAYwyGCObVtAf2On7hXiBwTN2HvueryF2jZlbixGMa84ReXMDTQKE7f2iuHqf8bh0yv/uH3rNUthFn5WWMi3GrYXZgHfunIZuruZZFyHjsVKMXPU0lBJ5HmOBD+pplHQp9hGLN6jtXsL2G9nsgqFxlREkwPLI6pcjB5PF1shLRSkhrUgLKCEZJSV0tSLaL/P7cPTABnvF3ycGX1TrYlDmguzFV4wopfKJJ7Ef8c8QQetgkpoZHeZpg+xhVm+9xMi8afyEAZSDJw5j2wLxafH8IO91HXg6Hx1rvCsDvxFFBD2yKGpRw+/tcSjKRRqpCwY+1kMIgbdLJfGItmjvDYiPvQtV7yDjgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
